# Configuration file for operator network training

# Random seed
seed: 42

# GPU index
gpu_idx: 0
# Model parameters
num_bases: 20
trunk_arch: [2, 100, 100, 100, 4]
branch_arch: [2, 100, 100, 100,  4]

# Training parameters
num_trunk_epochs: 500000 # both trunk and branch training iteration
num_LBFGS_epochs: 20000
lr_start: 0.002
lr_transition_steps: 10000
lr_decay_rate: 0.97
lr_end: 0.000002
eps: 0.00000001

## SOAP optimizer? should be already installed

# Dataset parameters
dataset_path: "/home/yeonjongshin/houtlaw/architecture_experiments/burgers_dataset.npz"
test_size: 0.2

# Output parameters (left blank for multiple models)
# save_path:

# Logging parameters
log_frequency: 10000
lbfgs_log_frequency: 1000

# classic [2]
# classic td [5]
# 2 step [7]
# 2 step td [8]

# 3,6,7