# Configuration file for operator network training

# Random seed
seed: 42

# GPU index
gpu_idx: 9
# Model parameters
num_bases: 4
trunk_arch: [2, 128, 128, 128, 4]
branch_arch: [2, 64, 64, 64,  4]

# Training parameters
num_trunk_epochs: 1500000 # both trunk and branch training iteration
num_LBFGS_epochs: 100000
lr_start: 0.02
lr_transition_steps: 10000
lr_decay_rate: 0.95
lr_end: 0.001
eps: 0.00000001

## SOAP optimizer? should be already installed

# Dataset parameters
dataset_path: "/home/yeonjongshin/houtlaw/architecture_experiments/burgers_dataset.npz"
test_size: 0.2

# Output parameters (left blank for multiple models)
# save_path:

# Logging parameters
log_frequency: 10000
lbfgs_log_frequency: 1000

# classic [2]
# classic td [5]
# 2 step [7]
# 2 step td [8]

# 3,6,7